# Generated by Django 5.2.7 on 2025-10-23 08:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Property title or name', max_length=200)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('flat', 'Flat'), ('bungalow', 'Bungalow'), ('terraced', 'Terraced House'), ('semi_detached', 'Semi-Detached House'), ('detached', 'Detached House'), ('studio', 'Studio'), ('maisonette', 'Maisonette'), ('other', 'Other')], default='house', max_length=20)),
                ('tenure', models.CharField(choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold'), ('share_of_freehold', 'Share of Freehold')], default='freehold', max_length=20)),
                ('address_line_1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('country', models.CharField(default='United Kingdom', max_length=50)),
                ('bedrooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('bathrooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('reception_rooms', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('total_floor_area', models.DecimalField(blank=True, decimal_places=2, help_text='Total floor area in square feet', max_digits=10, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Original purchase price in GBP', max_digits=12)),
                ('current_market_value', models.DecimalField(blank=True, decimal_places=2, help_text='Current estimated market value in GBP', max_digits=12, null=True)),
                ('monthly_rental_income', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rental income in GBP', max_digits=10, null=True)),
                ('description', models.TextField(help_text='Detailed property description', max_length=2000)),
                ('key_features', models.TextField(blank=True, help_text='Key features and highlights (one per line)', max_length=1000)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this property currently active/owned?')),
                ('is_rental', models.BooleanField(default=False, help_text='Is this property being rented out?')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('deed', 'Property Deed'), ('survey', 'Survey Report'), ('epc', 'Energy Performance Certificate'), ('insurance', 'Insurance Document'), ('lease', 'Lease Agreement'), ('mortgage', 'Mortgage Document'), ('other', 'Other Document')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='property_documents/%Y/%m/')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='user_home.property')),
            ],
            options={
                'ordering': ['document_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_main_image', models.BooleanField(default=False, help_text='Is this the main property image?')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user_home.property')),
            ],
            options={
                'ordering': ['-is_main_image', 'date_uploaded'],
            },
        ),
    ]
