# Generated by Django 5.2.6 on 2025-10-23 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='date_updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='property',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='property',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='country',
        ),
        migrations.RemoveField(
            model_name='property',
            name='county',
        ),
        migrations.RemoveField(
            model_name='property',
            name='current_market_value',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_rental',
        ),
        migrations.RemoveField(
            model_name='property',
            name='key_features',
        ),
        migrations.RemoveField(
            model_name='property',
            name='monthly_rental_income',
        ),
        migrations.RemoveField(
            model_name='property',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='reception_rooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='tenure',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
        migrations.RemoveField(
            model_name='property',
            name='total_floor_area',
        ),
        migrations.AddField(
            model_name='property',
            name='annual_income',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Total annual income from property', max_digits=8),
        ),
        migrations.AddField(
            model_name='property',
            name='car_parking_spaces',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='date_of_purchase',
            field=models.DateField(default=datetime.date(2022, 1, 1)),
        ),
        migrations.AddField(
            model_name='property',
            name='deposit_paid',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Initial deposit paid', max_digits=8),
        ),
        migrations.AddField(
            model_name='property',
            name='epc_rating',
            field=models.CharField(choices=[('A', 'A (Most Efficient)'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G (Least Efficient)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='estimated_market_value',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Estimated current market value', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='ground_rent',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Annual ground rent', max_digits=5),
        ),
        migrations.AddField(
            model_name='property',
            name='has_mortgage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='mortgage_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mortgage interest rate', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='mortgage_type',
            field=models.CharField(blank=True, choices=[('principal_and_interest', 'Principal & Interest'), ('interest_only', 'Interest Only')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='mortgage_years_remaining',
            field=models.PositiveIntegerField(blank=True, help_text='Years remaining on mortgage', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='number_bathrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='number_bedrooms',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='property',
            name='other_annual_costs',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Other annual costs (e.g., insurance, maintenance)', max_digits=8),
        ),
        migrations.AddField(
            model_name='property',
            name='outstanding_mortgage_balance',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Remaining mortgage balance', max_digits=8),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_status',
            field=models.CharField(choices=[('company', 'Property is owned in company'), ('individual', 'Property is owned in own name')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='property_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_management_fees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Property management fees as percentage of rental income', max_digits=4),
        ),
        migrations.AddField(
            model_name='property',
            name='property_name',
            field=models.CharField(default=1, help_text='Give your property a name for easy identification', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='service_charge',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Annual service charge', max_digits=5),
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='street_name',
            field=models.CharField(blank=True, default='Your Property Street', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='street_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='uk_resident',
            field=models.BooleanField(default=True, help_text='Is the property owner a UK resident?'),
        ),
        migrations.AddField(
            model_name='property',
            name='uk_taxfree_allowance',
            field=models.BooleanField(default=True, help_text='Is the property owner eligible for UK tax-free allowance?'),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='weekly_rent',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Current weekly rental income', max_digits=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, default='City', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='postcode',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('detached', 'Detached House'), ('apartment', 'Apartment'), ('semi', 'Semi-Detached House'), ('terrace', 'Terraced House'), ('end', 'End of Terrace'), ('bungalow', 'Bungalow'), ('cottage', 'Cottage')], default='semi', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='purchase_price',
            field=models.DecimalField(decimal_places=0, default=100000, help_text='Original purchase price', max_digits=8),
        ),
    ]
