# Generated by Django 5.2.6 on 2025-10-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0002_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_image',
            field=models.ImageField(blank=True, default='property_images/lexit_image.png', null=True, upload_to='property_images/'),
        ),
    ]
