# Generated by Django 5.2.6 on 2025-10-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0003_alter_property_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
