# Generated by Django 5.2.6 on 2025-11-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0004_alter_property_property_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(help_text='The main testimonial quote', max_length=500)),
                ('description', models.TextField(help_text='Detailed testimonial description', max_length=1000)),
                ('author_name', models.CharField(help_text='Name of the person giving the testimonial', max_length=100)),
                ('author_role', models.CharField(help_text='Job title or role of the testimonial author', max_length=100)),
                ('author_image', models.ImageField(blank=True, help_text='Photo of the testimonial author', null=True, upload_to='testimonials/')),
                ('social_media_link', models.URLField(blank=True, help_text='LinkedIn, Twitter, or other social media profile', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this testimonial should be displayed')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which testimonials should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
