# Generated by Django 5.2.6 on 2025-11-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0005_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='street_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
