# Generated by Django 5.2.7 on 2025-10-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='alt_text',
            field=models.CharField(default='News Article Image', max_length=100),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='banner',
            field=models.ImageField(blank=True, default='default_banner.jpg', upload_to=''),
        ),
    ]
