# Generated by Django 5.2.6 on 2025-10-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_alt_text_newsarticle_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='body',
            field=models.TextField(),
        ),
    ]
