# Generated by Django 5.2.6 on 2025-11-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsarticle_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-published_date']},
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('news', 'News'), ('article', 'Article')], default='news', max_length=10),
        ),
    ]
