# Generated by Django 5.2.6 on 2025-11-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsarticle_options_newsarticle_category'),
    ]

    operations = [
    ]
