# Generated by Django 5.2.6 on 2025-11-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20251108_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this article on the landing page'),
        ),
    ]
