# Generated by Django 5.2.6 on 2025-11-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newsarticle_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('news', 'News'), ('article', 'Article'), ('renters_rights', "Renters' Rights Act"), ('market', 'Market'), ('tech_news', 'Tech News'), ('rent_reviews', 'Rent Reviews'), ('taxes', 'Taxes')], default='news', max_length=20),
        ),
    ]
