# Generated by Django 5.2.7 on 2025-10-22 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, help_text='Upload your profile picture', null=True, upload_to='profile_images/')),
                ('avatar_choice', models.CharField(choices=[('default', 'Default Avatar'), ('avatar_1', 'Professional'), ('avatar_2', 'Casual'), ('avatar_3', 'Modern'), ('avatar_4', 'Elegant'), ('avatar_5', 'Creative')], default='default', help_text='Choose an avatar if you prefer not to upload a photo', max_length=20)),
                ('use_avatar', models.BooleanField(default=True, help_text='Use avatar instead of uploaded image')),
                ('country', models.CharField(choices=[('GB', 'United Kingdom'), ('AU', 'Australia'), ('BH', 'Bahrain'), ('BE', 'Belgium'), ('CA', 'Canada'), ('CN', 'China'), ('DE', 'Germany'), ('ES', 'Spain'), ('FJ', 'Fiji'), ('FR', 'France'), ('GH', 'Ghana'), ('HK', 'Hong Kong'), ('ID', 'Indonesia'), ('IE', 'Ireland'), ('IL', 'Israel'), ('IN', 'India'), ('IT', 'Italy'), ('JO', 'Jordan'), ('JP', 'Japan'), ('KE', 'Kenya'), ('KR', 'South Korea'), ('KW', 'Kuwait'), ('LB', 'Lebanon'), ('MY', 'Malaysia'), ('NG', 'Nigeria'), ('NL', 'Netherlands'), ('NZ', 'New Zealand'), ('OM', 'Oman'), ('PH', 'Philippines'), ('PT', 'Portugal'), ('QA', 'Qatar'), ('RU', 'Russia'), ('SA', 'Saudi Arabia'), ('SG', 'Singapore'), ('CH', 'Switzerland'), ('TH', 'Thailand'), ('TR', 'Turkey'), ('AE', 'United Arab Emirates'), ('US', 'United States'), ('VN', 'Vietnam'), ('ZA', 'South Africa'), ('OTHER', 'Other')], default='GB', help_text='Your country of residence', max_length=5)),
                ('city', models.CharField(blank=True, help_text='Your city (optional)', max_length=100, null=True)),
                ('retirement_objective', models.BooleanField(default=False, help_text='Investment for retirement planning')),
                ('income_objective', models.BooleanField(default=False, help_text='Investment for regular income generation')),
                ('capital_gain_objective', models.BooleanField(default=False, help_text='Investment for capital appreciation/growth')),
                ('accidental_landlord', models.BooleanField(default=False, help_text='Became a landlord by circumstance (e.g., inherited property, unable to sell)')),
                ('future_ownership', models.CharField(blank=True, choices=[('thinking_selling', 'I am thinking of selling'), ('long_haul', 'I am in it for the long haul'), ('right_price', 'I would sell at the right price'), ('get_me_out', 'Just get me out!')], help_text='Your future plans regarding property ownership', max_length=20, null=True)),
                ('facebook_url', models.URLField(blank=True, help_text='Your Facebook profile URL (optional)', null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='Your LinkedIn profile URL (optional)', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Your Twitter profile URL (optional)', null=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Your WhatsApp number with country code (e.g., +44 123 456 7890)', max_length=20, null=True)),
                ('bio', models.TextField(blank=True, help_text='Tell us a bit about yourself (optional, max 500 characters)', max_length=500, null=True)),
                ('website_url', models.URLField(blank=True, help_text='Your personal or business website (optional)', null=True)),
                ('show_email', models.BooleanField(default=False, help_text='Make your email visible to other users')),
                ('show_social_media', models.BooleanField(default=True, help_text='Make your social media links visible to other users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
