# Generated by Django 5.2.7 on 2025-11-11 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneypotAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the attempt')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the attempt occurred')),
                ('honeypot_field', models.CharField(help_text='Name of the honeypot field that was filled', max_length=100)),
                ('honeypot_value', models.TextField(blank=True, help_text='Value entered in the honeypot field')),
                ('form_data', models.JSONField(blank=True, default=dict, help_text='Other form data submitted')),
                ('path', models.CharField(help_text='URL path where attempt occurred', max_length=500)),
                ('referer', models.URLField(blank=True, help_text='HTTP referer header', null=True)),
                ('attempt_type', models.CharField(choices=[('honeypot', 'Honeypot Violation'), ('suspicious', 'Suspicious Activity'), ('bot', 'Bot Detection')], default='honeypot', help_text='Type of security violation', max_length=50)),
                ('blocked', models.BooleanField(default=True, help_text='Whether the attempt was blocked')),
            ],
            options={
                'verbose_name': 'Security Attempt',
                'verbose_name_plural': 'Security Attempts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('failed_login', 'Failed Login'), ('suspicious_user_agent', 'Suspicious User Agent'), ('rate_limit', 'Rate Limit Exceeded'), ('invalid_session', 'Invalid Session')], help_text='Type of security event', max_length=50)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address involved')),
                ('details', models.JSONField(default=dict, help_text='Event details')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('user', models.ForeignKey(blank=True, help_text='User account if known', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
